# Generated by Django 5.0 on 2023-12-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_taskcreated_not_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcreated',
            old_name='title',
            new_name='name',
        ),
    ]
